services:
  - type: web
    name: flask-api
    env: python
    plan: free
    branch: master
    buildCommand: "pip install -r requerimentos.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true